### ISSUE TITLE
0.0.6-SNAPSHOT fails in multi-project build

### ISSUE THREAD

**Issue by ben-manes** [tbroyer/gradle-errorprone-plugin-v0.0.x#7]
It appears that on a clean muti-project build the compiler does not see the project dependency classes and fails. If the plugin is applied to a prebuilt project, then the incremental compilation succeeds. This resulted in the plugin working locally, but failing on CI.

**Comment by tbroyer** [comment]
I have issues with some classes not being emitted (and therefore errors in downstream modules referencing those classes) but upstream modules are correctly put in the classpath in my tests.

Can you run with `--debug` and look for the `Compiling with args` line in the output? That'd help diagnose what goes wrong.

**Comment by ben-manes** [comment]
I see `Compiling with error-prone compiler` but no `Compiling with args` when running `gradle clean build -d 2>&1 | tee -a log`

**Comment by ben-manes** [comment]
oh, you probably meant `Compiler arguments`. See the [log](https://files.zenhub.io/54ce3743f748cd180f0817ab) file

**Comment by ben-manes** [comment]
Looking at `IntegerGenerator` failure, it is listed as a source file when errorprone compiles the `simulator` module. When compiling the `caffeine` tests which fail, the `simulator-1.0.0-SNAPSHOT.jar` is listed as a compiler argument. However, the `simuator/build/classes` does not contain the file so as you said it was not emitted.

**Comment by tbroyer** [comment]
That was an error-prone bug, fixed in 2.0.1-SNAPSHOT: google/error-prone@1f912d223295f55acca7456e46eea2a035e4629a

**Comment by tbroyer** [comment]
FYI: 2.0.1 has been released.

I'll test with Gradle 2.3-rc1 and release 0.0.6

**Comment by ben-manes** [comment]
great, let me take a look and try running it locally too. I should just need to find the right Maven coordinates to fetch 2.0.1

**Comment by ben-manes** [comment]
weird, I added `classpath "com.google.errorprone:error_prone_core:2.0.1"` to the buildscript classpath and a `gradle clean build` still fails with errorprone

**Comment by tbroyer** [comment]
Error-prone is not loaded in the build-script but from an `errorprone` configuration added to the project. It defaults to `latest.release` so Gradle should pick 2.0.1 automatically. See the README for how to customize it.

BTW, works for me with 2.3-rc-1.

**Comment by ben-manes** [comment]
yep, it works. I had to `--refresh-dependencies` to force the `latest.release` to be resolved

**Comment by tbroyer** [comment]
From https://server.org
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Even though I try not to introduce breaking changes, don't use dynamic versions (yet). I'll think about semver when I'll release 1.0(.0?)

That said, `[0.6,0.7)` or `[0.6,)` (depending on what you want) should work.
